name: Deploy site

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'

    - name: Copy HTML
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '*' --include '*.html' --content-type 'text/html'

    - name: Copy Turtle
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '*' --include '*.ttl' --content-type 'text/turtle'

    - name: Copy SVG
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '*' --include '*.svg' --content-type 'image/svg+xml'

    - name: Copy JPEG
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '*' --include '*.jpg' --content-type 'image/jpeg'
      
    - name: Copy PNG
      run: aws s3 sync . s3://${{ secrets.DEPLOY_AWS_S3_BUCKET }}/ --no-progress --acl public-read --follow-symlinks --delete --exclude '*' --include '*.png' --content-type 'image/png'
